FROM alpine:3.10 

ENV TERRAFORM_VERSION=0.14.7

ADD ./secrets/aws.creds .
ADD terraform-inventory.sh /usr/bin/
ADD ./ansible.sh /ansible.sh
ADD ansible /ansible
ADD ./secrets/id_rsa /root/.ssh/id_rsa

RUN apk update && apk add curl jq python bash ca-certificates git openssl unzip wget make go musl-dev openssh-client ansible && \
    cd /tmp && \
    wget https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip && \
    unzip terraform_${TERRAFORM_VERSION}_linux_amd64.zip -d /usr/bin && \
    git clone https://github.com/drew9781/terraform-inventory.git && \
    cd terraform-inventory && \
    go build . && \
    cp terraform-inventory /usr/bin/ && \
    cd /tmp && \
    mkdir /root/.aws && \
    cp /aws.creds /root/.aws/credentials && \
    ansible-galaxy install -r /ansible/requirements.yml && \
    rm -rf /tmp/* && \
    rm -rf /var/cache/apk/* && \
    rm -rf /var/tmp/* && \
    rm -rf /aws.creds && \
    chmod 600 /root/.ssh/id_rsa && \
    touch /test

